### ISSUE TITLE
Can't connect MongoDB Compass to MongoDB Atlas

### ISSUE THREAD

**Issue by yuito22suto** [yuito22suto/stunning-fortnight#1]
Atlas本体ではModelの確認ができるので問題なさそうではある
https://cloud.mongodb.com/v2/661d21d52e76f11b99a9db36#/metrics/replicaSet/661d23f9fe24b9426a98986e/explorer/movie-api-db/movies/find

**Comment by yitsturdy** [comment]
今日connectしたら無事できた
<img width="1440" alt="スクリーンショット 2024-04-18 20 08 18" src="https://github.com/yuito22suto/stunning-fortnight/assets/57525739/387c1423-c8bb-49d2-87e5-9cc69383fa13">
